version: '3.8'

services:
  # Celestia Bridge Node for AndeChain DA (replaces deprecated full node)
  celestia-bridge-node:
    image: ghcr.io/celestiaorg/celestia-node:v0.27.5-mocha
    container_name: celestia-bridge-node
    restart: unless-stopped
    ports:
      - "26658:26658"  # RPC API for AndeChain
      - "2121:2121"    # P2P
    volumes:
      - celestia-bridge-data:/home/celestia
      - ./celestia-full-init.sh:/opt/celestia-init.sh:ro
    env_file:
      - celestia-mocha.env
    entrypoint: /bin/sh
    command: ["/opt/celestia-init.sh"]
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:26658"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - ande-zk-network

networks:
  ande-zk-network:
    name: ande-zk-network
    driver: bridge

volumes:
  celestia-bridge-data:
    driver: local
