version: '3.8'

services:
  # Celestia Light Node connecting to QuickNode
  celestia-light-quicknode:
    image: ghcr.io/celestiaorg/celestia-node:v0.20.2-mocha
    container_name: celestia-light-quicknode
    restart: unless-stopped
    ports:
      - "26658:26658"  # RPC API for AndeChain
      - "2121:2121"    # P2P
    volumes:
      - celestia-light-quicknode-data:/home/celestia
      - ./celestia-light-quicknode.sh:/opt/celestia-init.sh:ro
    env_file:
      - celestia-mocha.env
    entrypoint: /bin/sh
    command: ["/opt/celestia-init.sh"]
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:26658"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    networks:
      - ande-zk-network

networks:
  ande-zk-network:
    name: ande-zk-network
    driver: bridge

volumes:
  celestia-light-quicknode-data:
    driver: local
