version: '3.8'

services:
  ibc-relayer:
    image: ghcr.io/cosmos/relayer:latest
    container_name: ibc-relayer
    restart: unless-stopped
    ports:
      - "3000:3000"  # REST API
      - "9090:9090"  # Metrics
    volumes:
      - ./relayer-config:/home/relayer/.relayer
      - relayer-data:/home/relayer/data
    environment:
      - RELAYER_LOG_LEVEL=info
      - RELAYER_METRICS_ADDR=0.0.0.0:9090
    command:
      - rly
      - start
      - andechain-celestia
    networks:
      - ande-zk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  relayer-api:
    build:
      context: ../relayer-api
      dockerfile: Dockerfile
    container_name: relayer-api
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - RELAYER_URL=http://ibc-relayer:3000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/relayer
    depends_on:
      - ibc-relayer
      - postgres
    networks:
      - ande-zk-network

  postgres:
    image: postgres:15-alpine
    container_name: relayer-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=relayer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ande-zk-network

networks:
  ande-zk-network:
    external: true

volumes:
  relayer-data:
    driver: local
  postgres-data:
    driver: local