services:
  # JWT initialization service
  jwt-init-sequencer:
    container_name: jwt-init-sequencer
    image: alpine:3.22.0
    volumes:
      - jwttoken-sequencer:/jwt
    healthcheck:
      test: [CMD, test, -f, /jwt/jwt.hex]
      interval: 5s
      timeout: 5s
      retries: 3
    command: >
      /bin/sh -c "mkdir -p /jwt &&
      if [ ! -f /jwt/jwt.hex ]; then
        apk add --no-cache openssl &&
        openssl rand -hex 32 | tr -d '\n' > /jwt/jwt.hex;
      fi"

  # ev-reth-sequencer con ANDE Token Duality
  ev-reth-sequencer:
    container_name: ev-reth-sequencer
    image: andelabs/ev-reth:latest
    pull_policy: never
    depends_on:
      jwt-init-sequencer:
        condition: service_completed_successfully
    env_file:
      - .env
      - .env.ande
    ports:
      - "8545:8545"
      - "9001:9001"
    restart: always
    volumes:
      - ./genesis.json:/root/genesis.json:ro
      - jwttoken-sequencer:/root/jwt:ro
      - ev-reth-sequencer-data:/root/reth
    entrypoint: /bin/sh -c
    command:
      - |
        echo "🚀 Starting ANDE-enabled ev-reth for AndeChain..."
        echo "📍 ANDE Precompile: 0x00000000000000000000000000000000000000FD"
        echo "🔗 Token Duality: ✅ Integrated"
        echo "⚡ Parallel EVM: ✅ Enabled"
        echo "🧠 MEV System: ✅ Ready"
        echo "📦 Build: 2025-10-14 (368ad84)"
        echo ""

         ev-reth node \
         --chain /root/genesis.json \
         --http \
         --http.addr 0.0.0.0 \
         --http.port 8545 \
         --http.api "admin,eth,net,web3,txpool,debug,trace" \
         --http.corsdomain "*" \
         --authrpc.addr 0.0.0.0 \
         --authrpc.port 8551 \
         --authrpc.jwtsecret /root/jwt/jwt.hex \
         --datadir /root/reth
    networks:
      - ande-network

  # Evolve sequencer - Componente de consenso y producción de bloques
  evolve-sequencer:
    container_name: evolve-sequencer
    image: ghcr.io/evstack/ev-node-evm-single:main
    pull_policy: always
    depends_on:
      ev-reth-sequencer:
        condition: service_started
      local-da:
        condition: service_started
      jwt-init-sequencer:
        condition: service_completed_successfully
    env_file:
      - .env
    restart: always
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "🚀 Initializing Evolve sequencer for AndeChain..."
        
        # Read JWT secret
        JWT_SECRET=$$(cat /root/jwt/jwt.hex)
        echo "📝 JWT Secret loaded: $${JWT_SECRET:0:10}..."
        
        # Initialize evolve config if not exists
        if [ ! -f "/root/.evolve/config/evnode.yaml" ]; then
            echo "📝 Initializing evolve config..."
            evm-single init \
                --home=/root/.evolve \
                --evnode.node.aggregator=true \
                --evnode.signer.passphrase=secret \
                --evnode.da.address=http://local-da:7980 \
                --evnode.node.block_time=2s
        fi
        
        echo "🚀 Starting Evolve sequencer..."
        exec evm-single start \
            --home=/root/.evolve \
            --evm.eth-url=http://ev-reth-sequencer:8545 \
            --evm.engine-url=http://ev-reth-sequencer:8551 \
            --evm.jwt-secret="$$JWT_SECRET" \
            --evm.genesis-hash=0xf2bbf7248c3a5c0788b31525c7a725376e566f1bdfcfb924bb7c548e92476dfb \
            --evnode.node.aggregator=true \
            --evnode.da.address=http://local-da:7980 \
            --evnode.signer.passphrase=secret
    volumes:
      - jwttoken-sequencer:/root/jwt:ro
      - evolve-sequencer-data:/root/.evolve
    ports:
      - "26661:26660"
    networks:
      - ande-network

  # Local DA service - Mock de Celestia para desarrollo
  local-da:
    image: ghcr.io/andelabs/andechain-local-da:develop
    container_name: local-da
    restart: unless-stopped
    command: ["-listen-all", "-port", "7980"]
    ports:
      - "7980:7980"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:7980"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - ande-network

  # Single sequencer - Metrics exporter placeholder
  # Real sequencer with full metrics coming in next update
  single-sequencer:
    container_name: single-sequencer
    image: prom/node-exporter:latest
    ports:
      - "26660:9100"
    restart: always
    depends_on:
      ev-reth-sequencer:
        condition: service_started
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - ande-network

networks:
  ande-network:
    name: ande-network
    driver: bridge

volumes:
  jwttoken-sequencer:
    driver: local
  ev-reth-sequencer-data:
    driver: local
  evolve-sequencer-data:
    driver: local
  sequencer-data:
    driver: local
  sequencer-export:
    name: sequencer-export
    driver: local
