FROM python:3.11-alpine

WORKDIR /app

RUN pip install --no-cache-dir requests

COPY celestia-exporter.py /app/celestia-exporter.py

RUN chmod +x /app/celestia-exporter.py

EXPOSE 9100

CMD ["python3", "/app/celestia-exporter.py"]
