---
services:
  # JWT initialization service (unchanged)
  jwt-init-sequencer:
    container_name: jwt-init-sequencer
    image: alpine:3.22.0
    volumes:
      - jwttoken-sequencer:/jwt
    healthcheck:
      test: [CMD, test, -f, /jwt/jwt.hex]
      interval: 5s
      timeout: 5s
      retries: 3
    command: >
      /bin/sh -c "mkdir -p /jwt &&
      if [ ! -f /jwt/jwt.hex ]; then
        apk add --no-cache openssl &&
        openssl rand -hex 32 | tr -d '\n' > /jwt/jwt.hex;
      fi"

  # 🆕 CUSTOM ev-reth-sequencer con ANDE Token Duality
  ev-reth-sequencer:
    container_name: ev-reth-sequencer
    build:
      context: ../../../..
      dockerfile: andechain/Dockerfile.evm
    depends_on:
      jwt-init-sequencer:
        condition: service_completed_successfully
    env_file:
      - .env
      - ../../.env.ande
    ports:
      - $SEQUENCER_EV_RETH_PROMETHEUS_PORT:9001
      - "8545:8545"
    restart: always
    volumes:
      # Montamos nuestro archivo de génesis
      - ./genesis.final.json:/root/genesis.json:ro
      # Montamos el secreto JWT
      - jwttoken-sequencer:/root/jwt:ro
      # Persistencia de datos
      - ev-reth-sequencer-data:/root/reth
    entrypoint: /bin/sh -c
    command:
      - |
          echo "🚀 Starting ANDE-enabled ev-reth for AndeChain..."
          echo "📍 Precompile Address: 0x00000000000000000000000000000000000000FD"
          echo "🔗 ANDE Integration: v0.3.0 - Type alias pattern"
          echo ""

          ev-reth node \
          --ev-reth.enable \
          --chain /root/genesis.json \
          --metrics 0.0.0.0:9001 \
          --log.file.directory /root/logs \
          --authrpc.addr 0.0.0.0 \
          --authrpc.port 8551 \
          --authrpc.jwtsecret /root/jwt/jwt.hex \
          --http --http.addr 0.0.0.0 --http.port 8545 \
          --http.api "admin,eth,net,web3,txpool,debug" \
          --http.corsdomain "*" \
          --disable-discovery \
          --txpool.pending-max-count 200000 \
          --txpool.pending-max-size 200 \
          --txpool.queued-max-count 200000 \
          --txpool.queued-max-size 200 \
          --txpool.max-account-slots 2048 \
          --txpool.max-new-txns 2048 \
          --txpool.additional-validation-tasks 16 \
          --datadir /root/reth \
          --dev
    networks:
      - evstack_shared

  # Local DA service for data availability
  local-da:
    build:
      context: ../../stacks/da-local/ev-node
      dockerfile: ./da/cmd/local-da/Dockerfile
    container_name: local-da
    restart: unless-stopped
    ports:
      - "7980:7980"
    networks:
      - evstack_shared

  # Single sequencer (unchanged)
  single-sequencer:
    container_name: single-sequencer
    image: ghcr.io/evstack/ev-node-evm-single:main
    env_file: .env
    ports:
      - $SEQUENCER_EV_NODE_PROMETHEUS_PORT:26660
    restart: always
    depends_on:
      ev-reth-sequencer:
        condition: service_started
      local-da:
        condition: service_started
    volumes:
      - sequencer-data:/root/.evm-single
      - jwttoken-sequencer:/root/jwt:ro
      - sequencer-export:/volumes/sequencer_export
      - ./entrypoint.sequencer.sh:/usr/bin/entrypoint.sh
      - ../../lib/logging.sh:/usr/local/lib/logging.sh:ro
    command:
      - start
      - --rollkit.rpc.address=0.0.0.0:7331
      - --rollkit.p2p.listen_address=/ip4/0.0.0.0/tcp/7676
      - --rollkit.instrumentation.prometheus
      - --rollkit.instrumentation.prometheus_listen_addr=:26660
    environment:
      - EVM_ENGINE_URL=http://ev-reth-sequencer:8551
      - EVM_ETH_URL=http://ev-reth-sequencer:8545
      - EVM_JWT_PATH=/root/jwt/jwt.hex
      - EVM_BLOCK_TIME=500ms
      - EVM_SIGNER_PASSPHRASE=${EVM_SIGNER_PASSPHRASE}
      - DA_BLOCK_TIME=30s
      - DA_ADDRESS=http://local-da:7980
    networks:
      - evstack_shared

networks:
  evstack_shared:
    name: evstack_shared
    external: true

volumes:
  jwttoken-sequencer:
    driver: local
  ev-reth-sequencer-data:
    driver: local
  sequencer-data:
    driver: local
  sequencer-export:
    name: sequencer-export
    driver: local