services:
  # JWT initialization service for testnet
  jwt-init-testnet:
    container_name: jwt-init-testnet
    image: alpine:3.22.0
    volumes:
      - jwttoken-testnet:/jwt
    healthcheck:
      test: [CMD, test, -f, /jwt/jwt.hex]
      interval: 5s
      timeout: 5s
      retries: 3
    command: >
      /bin/sh -c "mkdir -p /jwt &&
      if [ ! -f /jwt/jwt.hex ]; then
        apk add --no-cache openssl &&
        openssl rand -hex 32 | tr -d '\n' > /jwt/jwt.hex;
      fi"

  # ev-reth-sequencer for testnet with MEV and Parallel Execution
  ev-reth-testnet:
    container_name: ev-reth-testnet
    build:
      context: ../../..
      dockerfile: Dockerfile.evm
    depends_on:
      jwt-init-testnet:
        condition: service_completed_successfully
    env_file:
      - .env.testnet
      - .env.ande.testnet
    ports:
      - "8545:8545"
      - "8546:8546"
      - "9001:9001"
      - "9002:9002"
    restart: always
    volumes:
      - ./genesis.json:/root/genesis.json:ro
      - jwttoken-testnet:/root/jwt:ro
      - ev-reth-testnet-data:/root/reth
      - ev-reth-testnet-logs:/root/logs
    entrypoint: /bin/sh -c
    command:
      - |
        echo "🚀 Starting ANDE-enabled ev-reth for AndeChain Testnet..."
        echo "📍 Precompile Address: 0x00000000000000000000000000000000000000FD"
        echo "🔗 ANDE Integration: Type alias pattern"
        echo "⚡ MEV System: Enabled"
        echo "🔄 Parallel Execution: Enabled"
        echo "📊 Monitoring: Prometheus + Grafana"
        echo ""

        ev-reth node \
        --chain /root/genesis.json \
        --metrics 0.0.0.0:9001 \
        --log.file.directory /root/logs \
        --authrpc.addr 0.0.0.0 \
        --authrpc.port 8551 \
        --authrpc.jwtsecret /root/jwt/jwt.hex \
        --http --http.addr 0.0.0.0 --http.port 8545 \
        --http.api "admin,eth,net,web3,txpool,debug" \
        --http.corsdomain "*" \
        --ws --ws.addr 0.0.0.0 --ws.port 8546 \
        --ws.api "admin,eth,net,web3,txpool,debug" \
        --ws.origins "*" \
        --disable-discovery \
        --txpool.pending-max-count 100000 \
        --datadir /root/reth \
        --dev
    networks:
      - ande-testnet-network

  # Local DA service for testnet
  local-da-testnet:
    image: ghcr.io/andelabs/andechain-local-da:develop
    container_name: local-da-testnet
    restart: unless-stopped
    ports:
      - "7980:7980"
    networks:
      - ande-testnet-network

  # Single sequencer for testnet
  single-sequencer-testnet:
    container_name: single-sequencer-testnet
    image: ghcr.io/evstack/ev-node-evm-single:main
    env_file: .env.testnet
    ports:
      - "26660:26660"
      - "30303:30303"
    restart: always
    depends_on:
      ev-reth-testnet:
        condition: service_started
      local-da-testnet:
        condition: service_started
    volumes:
      - sequencer-testnet-data:/root/.evm-single
      - jwttoken-testnet:/root/jwt:ro
      - sequencer-testnet-export:/volumes/sequencer_export
      - ./entrypoint.sequencer.sh:/usr/bin/entrypoint.sh
      - ../../lib/logging.sh:/usr/local/lib/logging.sh:ro
    command:
      - start
      - --evnode.rpc.address=0.0.0.0:7331
      - --evnode.p2p.listen_address=/ip4/0.0.0.0/tcp/7676
      - --evnode.instrumentation.prometheus
      - --evnode.instrumentation.prometheus_listen_addr=:26660
    environment:
      - EVM_ENGINE_URL=http://ev-reth-testnet:8551
      - EVM_ETH_URL=http://ev-reth-testnet:8545
      - EVM_JWT_PATH=/root/jwt/jwt.hex
      - EVM_BLOCK_TIME=2s
      - EVM_SIGNER_PASSPHRASE=${EVM_SIGNER_PASSPHRASE}
      - DA_BLOCK_TIME=30s
      - DA_ADDRESS=http://local-da-testnet:7980
      - TESTNET_MODE=true
    networks:
      - ande-testnet-network

  # Prometheus for testnet monitoring
  prometheus-testnet:
    container_name: prometheus-testnet
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.testnet.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-testnet-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - ande-testnet-network

  # Grafana for testnet visualization
  grafana-testnet:
    container_name: grafana-testnet
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-testnet-data:/var/lib/grafana
      - ./grafana.testnet.ini:/etc/grafana/grafana.ini:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=ande_testnet_2025
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - ande-testnet-network

networks:
  ande-testnet-network:
    name: ande-testnet-network
    driver: bridge

volumes:
  jwttoken-testnet:
    driver: local
  ev-reth-testnet-data:
    driver: local
  ev-reth-testnet-logs:
    driver: local
  sequencer-testnet-data:
    driver: local
  sequencer-testnet-export:
    name: sequencer-testnet-export
    driver: local
  prometheus-testnet-data:
    driver: local
  grafana-testnet-data:
    driver: local