# =========================================================================
# ANDE CHAIN - PRODUCTION MONITORING CONFIGURATION
# =========================================================================
# Comprehensive monitoring suite for production rollup operations
# Integrates: Prometheus, Grafana, Alertmanager, and custom metrics
# =========================================================================

# =========================================================================
# PROMETHEUS SCRAPE CONFIGURATION
# =========================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'andechain-production'
    environment: 'mainnet'
    chain_id: '6174'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/alert.rules.yml'
  - '/etc/prometheus/mev.rules.yml'
  - '/etc/prometheus/performance.rules.yml'

# =========================================================================
# SCRAPE JOBS
# =========================================================================

scrape_configs:

  # -----------------------------------------------------------------------
  # 1. EV-RETH EXECUTION CLIENT METRICS
  # -----------------------------------------------------------------------
  - job_name: 'ev-reth-sequencer'
    static_configs:
      - targets: ['ev-reth-sequencer:9001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ev-reth-sequencer'
      - target_label: component
        replacement: 'execution-client'

  # -----------------------------------------------------------------------
  # 2. EVOLVE SEQUENCER METRICS
  # -----------------------------------------------------------------------
  - job_name: 'evolve-sequencer'
    static_configs:
      - targets: ['evolve-sequencer:26660']
    metrics_path: '/metrics'
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'evolve-sequencer'
      - target_label: component
        replacement: 'consensus-layer'

  # -----------------------------------------------------------------------
  # 3. PARALLEL EVM METRICS (Custom Port)
  # -----------------------------------------------------------------------
  - job_name: 'parallel-evm'
    static_configs:
      - targets: ['ev-reth-sequencer:9091']
    metrics_path: '/metrics'
    scrape_interval: 5s  # Higher frequency for performance metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'parallel-evm'
      - target_label: component
        replacement: 'parallel-execution'

  # -----------------------------------------------------------------------
  # 4. MEV INTEGRATION METRICS (Custom Port)
  # -----------------------------------------------------------------------
  - job_name: 'mev-integration'
    static_configs:
      - targets: ['ev-reth-sequencer:9092']
    metrics_path: '/mev-metrics'
    scrape_interval: 5s  # High frequency for MEV detection
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'mev-integration'
      - target_label: component
        replacement: 'mev-system'

  # -----------------------------------------------------------------------
  # 5. CELESTIA LIGHT NODE METRICS
  # -----------------------------------------------------------------------
  - job_name: 'celestia-light'
    static_configs:
      - targets: ['celestia-light:26658']
    metrics_path: '/metrics'
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'celestia-light'
      - target_label: component
        replacement: 'data-availability'

  # -----------------------------------------------------------------------
  # 6. PROMETHEUS SELF-MONITORING
  # -----------------------------------------------------------------------
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # -----------------------------------------------------------------------
  # 7. GRAFANA METRICS
  # -----------------------------------------------------------------------
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # -----------------------------------------------------------------------
  # 8. CADVISOR (CONTAINER METRICS)
  # -----------------------------------------------------------------------
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    relabel_configs:
      - target_label: component
        replacement: 'infrastructure'

  # -----------------------------------------------------------------------
  # 9. NODE EXPORTER (SYSTEM METRICS)
  # -----------------------------------------------------------------------
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 30s
    relabel_configs:
      - target_label: component
        replacement: 'system'

  # -----------------------------------------------------------------------
  # 10. NGINX PROXY METRICS
  # -----------------------------------------------------------------------
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-proxy:9113']
    metrics_path: '/metrics'
    scrape_interval: 30s
    relabel_configs:
      - target_label: component
        replacement: 'reverse-proxy'

  # -----------------------------------------------------------------------
  # 11. POSTGRES DATABASE METRICS (If using)
  # -----------------------------------------------------------------------
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'
    scrape_interval: 30s
    relabel_configs:
      - target_label: component
        replacement: 'database'

  # -----------------------------------------------------------------------
  # 12. CUSTOM APPLICATION METRICS
  # -----------------------------------------------------------------------
  - job_name: 'custom-metrics'
    static_configs:
      - targets: ['metrics-aggregator:9094']
    metrics_path: '/metrics'
    scrape_interval: 15s

# =========================================================================
# METRIC RELABELING (Global)
# =========================================================================

metric_relabel_configs:
  # Drop high-cardinality debug metrics in production
  - source_labels: [__name__]
    regex: 'debug_.*'
    action: drop
  
  # Add chain identifier
  - target_label: chain
    replacement: 'andechain'

# =========================================================================
# REMOTE WRITE (Optional - for long-term storage)
# =========================================================================

# Uncomment to enable remote write to external storage
# remote_write:
#   - url: 'https://your-remote-prometheus.example.com/api/v1/write'
#     basic_auth:
#       username: 'andechain'
#       password: 'your-secure-password'
#     queue_config:
#       capacity: 10000
#       max_shards: 5
#       max_samples_per_send: 1000

# =========================================================================
# STORAGE CONFIGURATION
# =========================================================================

storage:
  tsdb:
    # Data retention period
    retention.time: 30d
    
    # Maximum storage size (automatically delete old data when exceeded)
    retention.size: 50GB
    
    # Data directory
    path: /prometheus
    
    # Enable compression
    wal-compression: true

# =========================================================================
# END OF PROMETHEUS CONFIGURATION
# =========================================================================
