# =========================================================================
# ANDE CHAIN - PROMETHEUS ALERT RULES
# =========================================================================
# Production-grade alerting for critical system conditions
# =========================================================================

groups:

# =========================================================================
# 1. BLOCKCHAIN HEALTH ALERTS
# =========================================================================
- name: blockchain_health
  interval: 30s
  rules:
    
    # Block production stopped
    - alert: BlockProductionStopped
      expr: increase(eth_block_number[5m]) == 0
      for: 2m
      labels:
        severity: critical
        component: consensus
      annotations:
        summary: "Block production has stopped"
        description: "No new blocks produced in the last 2 minutes on ANDE Chain"

    # Block time too high (lazy mode should be 5s max)
      - alert: BlockTimeTooHigh
      expr: rate(eth_block_number[1m]) < 0.1  # Less than 1 block per 10s
      for: 3m
      labels:
        severity: warning
        component: consensus
      annotations:
        summary: "Block production is slower than expected"
        description: "Average block time exceeded 10 seconds (expected: 1-5s adaptive)"

    # No transactions for extended period (potential issue)
    - alert: NoTransactionsExtended
      expr: rate(eth_transactions_total[15m]) == 0
      for: 15m
      labels:
        severity: info
        component: mempool
      annotations:
        summary: "No transactions detected for 15 minutes"
        description: "The network has not processed any transactions recently"

# =========================================================================
# 2. PARALLEL EVM ALERTS
# =========================================================================
- name: parallel_evm
  interval: 15s
  rules:
    
    # Parallel execution failure rate too high
    - alert: HighParallelExecutionFailures
      expr: rate(parallel_execution_failures_total[5m]) > 0.1
      for: 2m
      labels:
        severity: warning
        component: parallel-evm
      annotations:
        summary: "High parallel execution failure rate"
        description: "Parallel execution failure rate is {{ $value | humanizePercentage }}"

    # Worker thread crashes
    - alert: WorkerThreadCrashed
      expr: increase(parallel_worker_crashes_total[5m]) > 0
      for: 1m
      labels:
        severity: critical
        component: parallel-evm
      annotations:
        summary: "Parallel EVM worker thread crashed"
        description: "{{ $value }} worker threads crashed in the last 5 minutes"

    # High worker utilization (may need more workers)
    - alert: HighWorkerUtilization
      expr: avg(parallel_worker_utilization) > 0.90
      for: 5m
      labels:
        severity: warning
        component: parallel-evm
      annotations:
        summary: "Worker threads are highly utilized"
        description: "Average worker utilization is {{ $value | humanizePercentage }} - consider increasing concurrency_level"

    # Low parallelism ratio
    - alert: LowParallelismRatio
      expr: parallel_execution_ratio < 0.5
      for: 10m
      labels:
        severity: info
        component: parallel-evm
      annotations:
        summary: "Low parallel execution ratio"
        description: "Only {{ $value | humanizePercentage }} of transactions are executed in parallel"

# =========================================================================
# 3. MEV SYSTEM ALERTS
# =========================================================================
- name: mev_system
  interval: 30s
  rules:
    
    # Large MEV opportunity detected
    - alert: LargeMEVOpportunity
      expr: mev_opportunity_value > 10000000000000000000  # 10 ANDE
      for: 1m
      labels:
        severity: info
        component: mev
      annotations:
        summary: "Large MEV opportunity detected"
        description: "MEV opportunity of {{ $value | humanize }} wei detected"

    # MEV distribution failed
    - alert: MEVDistributionFailed
      expr: increase(mev_distribution_failures_total[10m]) > 0
      for: 1m
      labels:
        severity: critical
        component: mev
      annotations:
        summary: "MEV distribution to stakers failed"
        description: "{{ $value }} MEV distribution attempts failed"

    # MEV buffer too high (should auto-deposit)
    - alert: MEVBufferTooHigh
      expr: mev_buffer_amount > 500000000000000000000  # 500 ANDE
      for: 5m
      labels:
        severity: warning
        component: mev
      annotations:
        summary: "MEV buffer is too high"
        description: "MEV buffer contains {{ $value | humanize }} wei - should trigger auto-deposit"

    # Auction failures
    - alert: MEVAuctionFailures
      expr: rate(mev_auction_failures_total[5m]) > 0.05
      for: 2m
      labels:
        severity: warning
        component: mev
      annotations:
        summary: "MEV auctions are failing"
        description: "{{ $value | humanizePercentage }} of MEV auctions failed"

# =========================================================================
# 4. DATA AVAILABILITY (CELESTIA) ALERTS
# =========================================================================
- name: data_availability
  interval: 30s
  rules:
    
    # DA submission failures
    - alert: DASubmissionFailures
      expr: rate(da_submission_failures_total[5m]) > 0.1
      for: 2m
      labels:
        severity: critical
        component: data-availability
      annotations:
        summary: "High DA submission failure rate"
        description: "{{ $value | humanizePercentage }} of DA submissions are failing"

    # Celestia node disconnected
    - alert: CelestiaNodeDisconnected
      expr: celestia_node_connected == 0
      for: 1m
      labels:
        severity: critical
        component: data-availability
      annotations:
        summary: "Celestia light node is disconnected"
        description: "Cannot submit data to Celestia DA layer"

    # High DA gas costs
    - alert: HighDAGasCosts
      expr: avg(da_submission_gas_cost[1h]) > 0.01  # Adjust threshold
      for: 30m
      labels:
        severity: warning
        component: data-availability
      annotations:
        summary: "DA gas costs are high"
        description: "Average DA gas cost is {{ $value }} - consider adjusting gas_multiplier"

    # DA batch queue buildup
    - alert: DABatchQueueBuildup
      expr: da_batch_queue_size > 100
      for: 5m
      labels:
        severity: warning
        component: data-availability
      annotations:
        summary: "DA batch queue is building up"
        description: "{{ $value }} batches waiting for DA submission"

# =========================================================================
# 5. RESOURCE ALERTS
# =========================================================================
- name: resource_usage
  interval: 60s
  rules:
    
    # High CPU usage
    - alert: HighCPUUsage
      expr: avg(rate(container_cpu_usage_seconds_total[5m])) by (container_label_com_docker_compose_service) > 0.80
      for: 5m
      labels:
        severity: warning
        component: infrastructure
      annotations:
        summary: "High CPU usage on {{ $labels.container_label_com_docker_compose_service }}"
        description: "CPU usage is {{ $value | humanizePercentage }}"

    # High memory usage
    - alert: HighMemoryUsage
      expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.85
      for: 5m
      labels:
        severity: warning
        component: infrastructure
      annotations:
        summary: "High memory usage on {{ $labels.container_label_com_docker_compose_service }}"
        description: "Memory usage is {{ $value | humanizePercentage }} of limit"

    # Disk space low
    - alert: DiskSpaceLow
      expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.15
      for: 5m
      labels:
        severity: critical
        component: infrastructure
      annotations:
        summary: "Low disk space on {{ $labels.device }}"
        description: "Only {{ $value | humanizePercentage }} disk space remaining"

# =========================================================================
# 6. NETWORK & RPC ALERTS
# =========================================================================
- name: network_rpc
  interval: 30s
  rules:
    
    # High RPC error rate
    - alert: HighRPCErrorRate
      expr: rate(rpc_errors_total[5m]) > 0.05
      for: 2m
      labels:
        severity: warning
        component: rpc
      annotations:
        summary: "High RPC error rate"
        description: "RPC error rate is {{ $value | humanizePercentage }}"

    # RPC response time high
    - alert: SlowRPCResponses
      expr: histogram_quantile(0.95, rate(rpc_request_duration_seconds_bucket[5m])) > 1.0
      for: 5m
      labels:
        severity: warning
        component: rpc
      annotations:
        summary: "RPC responses are slow"
        description: "95th percentile RPC response time is {{ $value }}s"

    # No peer connections
    - alert: NoPeerConnections
      expr: net_peer_count == 0
      for: 2m
      labels:
        severity: critical
        component: network
      annotations:
        summary: "No peer connections"
        description: "Node has no peer connections"

# =========================================================================
# 7. ANDE TOKEN DUALITY ALERTS
# =========================================================================
- name: ande_token_duality
  interval: 30s
  rules:
    
    # Precompile call failures
    - alert: AndePrecompileFailures
      expr: rate(ande_precompile_failures_total[5m]) > 0.01
      for: 2m
      labels:
        severity: warning
        component: token-duality
      annotations:
        summary: "ANDE precompile calls are failing"
        description: "{{ $value | humanizePercentage }} of precompile calls failed"

    # High lazy update queue
    - alert: HighLazyUpdateQueue
      expr: ande_lazy_update_queue_size > 1000
      for: 5m
      labels:
        severity: warning
        component: token-duality
      annotations:
        summary: "Lazy update queue is building up"
        description: "{{ $value }} pending lazy balance updates"

# =========================================================================
# END OF ALERT RULES
# =========================================================================
